micronaut:
  application:
    name: padletNotifier
  server:
    port: 8080
    thread-selection: AUTO
  data:
    pageable:
      max-page-size: 1000
  http:
    client:
      read-timeout: 20s
      exception-on-error-status: false

jackson:
  bean-introspection-module: true
  serialization-inclusion: always

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/padletnotify
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: none
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
